name: PR Testing

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install nx
        run: npm install -g nx
      - name: Install dependencies
        run: yarn
      - name: Run lint
        run: nx lint website
      - name: Run website tests
        run: nx test website
      - name: Run e2e tests
        run: nx e2e website-e2e
